language: csharp
solution: ./Sources/AutoMonkey/AutoMonkey.sln
mono: none
dotnet: 1.0.3
dist: trusty

install:
  - sudo apt-get install nunit-console

script:
  - dotnet restore
  - xbuild ./Sources/AutoMonkey/AutoMonkey.sln
  - nunit-console ./Sources/AutoMonkey/AMCanUsbLibTest/bin/Debug/AMCanUsbLibTest.dll
  - nunit-console ./Sources/AutoMonkey/AMLinLibTest/bin/Debug/AMLinLibTest.dll
  - nunit-console ./Sources/AutoMonkey/AMLogEngineLibTest/bin/Debug/AMLogEngineLibTest.dll
  - nunit-console ./Sources/AutoMonkey/AutoMonkeyTest/bin/Debug/AutoMonkeyTest.dll
