version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

before_build:
    - nuget restore ./Sources/AutoMonkey/AutoMonkey.sln

build:
  project: ./Sources/AutoMonkey/AutoMonkey.sln
  verbosity: minimal

# scripts to run before tests
before_test:
  - echo ========= Runing unit tests ===============

# to run tests again only selected assemblies and/or categories
test:
  assemblies:
    only:
      - '**\*Test.dll'
    
