version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

install: 
  - cmd: >- 
   nuget install NUnit.Console -Version 3.5.0 -OutputDirectory C:\Tools\NUnit35
   set path=C:\Tools\NUnit35\NUnit.ConsoleRunner.3.5.0\tools\;%path%
   mkdir C:\Tools\NUnit35\NUnit.ConsoleRunner.3.5.0\tools\addins
   copy C:\Tools\NUnit3\bin\addins C:\Tools\NUnit35\NUnit.ConsoleRunner.3.5.0\tools\addins
   copy C:\Tools\NUnit3\bin\appveyor.addins C:\Tools\NUnit35\NUnit.ConsoleRunner.3.5.0\tools



before_build:
    - nuget restore ./Sources/AutoMonkey/AutoMonkey.sln

build:
  project: ./Sources/AutoMonkey/AutoMonkey.sln
  verbosity: minimal

# scripts to run before tests
before_test:
  - echo ========= Runing unit tests ===============

# to run tests again only selected assemblies and/or categories
test:
  assemblies:
    only:
      - '**\*Test.dll'
    
test_script:
- cmd: nunit3-console "C:\projects\automonkeyproject\Sources\AutoMonkey\AMCanUsbLibTest\bin\Debug\AMCanUsbLibTest.dll" "C:\projects\automonkeyproject\Sources\AutoMonkey\AMLinLibTest\bin\Debug\AMLinLibTest.dll" "C:\projects\automonkeyproject\Sources\AutoMonkey\AMLogEngineLibTest\bin\Debug\AMLogEngineLibTest.dll" "C:\projects\automonkeyproject\Sources\AutoMonkey\AutoMonkeyTest\bin\Debug\AutoMonkeyTest.dll"
