version: 0.0.{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

branches:
  only:
    - master

skip_tags: true

skip_commits:
  message: /README.md edited online/
 
image: 
  - Visual Studio 2017
  
before_build:
    - nuget restore ./Sources/AutoMonkey/AutoMonkey.sln

configuration: Debug
    
build:
  project: ./Sources/AutoMonkey/AutoMonkey.sln
  verbosity: minimal

test:
  assemblies:
    - '**\*Test.dll'

artifacts:
  - path: '**\*Lib\bin\*\AM*Lib.dll'
    name: AutoMonkeyLib
    type: zip
    
  - path: '**\bin\*\**Logger.dll'
    name: AutoMonkeyLib
    type: zip
  
  - path: '**\AutoMonkey\bin\*\AutoMonkey.exe'
    name: AutoMonkey
    type: zip

  
 