version: 0.0.{build}

# branches to build
branches:
  only:
    - master

before_build:
    - nuget restore ./Sources/AutoMonkey/AutoMonkey.sln

build:
  project: ./Sources/AutoMonkey/AutoMonkey.sln
  verbosity: minimal

# scripts to run before tests
before_test: none

# to run tests again only selected assemblies and/or categories
test: none

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: ./Sources/AutoMonkey/AutoMonkey/bin/Debug
    name: AutoMonkey.exe
 