version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

before_build:
    - nuget restore src\CommandLineApplicationLauncher.sln

build:
  project: ./Sources/AutoMonkey/AutoMonkey.sln
  verbosity: minimal
test:
  assemblies: '**\*Test.dll'


