version: 0.0.{build}

# branches to build
branches:
  only:
    - master

skip_tags: true

skip_commits:
  message: /README.md edited online/
 
cache:
  - packages -> **\packages.config
  - C:\downloads -> appveyor.yml

 image: Visual Studio 2017
  
before_build:
    - nuget restore ./Sources/AutoMonkey/AutoMonkey.sln

build:
  project: ./Sources/AutoMonkey/AutoMonkey.sln
  verbosity: minimal

# scripts to run before tests
before_test: none

# to run tests again only selected assemblies and/or categories
#test: none

test:
  assemblies:
    - '**\*Test.dll'

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: 
     - '**\*.dll' 
     - '**\*.exe' 
    name: AutoMonkey
 