version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

before_build:
    - nuget restore ./Sources/AutoMonkey/AutoMonkey.sln

build:
  project: ./Sources/AutoMonkey/AutoMonkey.sln
  verbosity: minimal

# scripts to run before tests
before_test:
  - echo ========= Runing unit tests ===============

test:
  assemblies:
  - '**\*Test.dll'

test_script:
- cmd: >-
    nunit-console C:\projects\automonkeyproject\Sources\AutoMonkey\AMCanUsbLibTest\bin\Debug\AMCanUsbLibTest.dll
    nunit-console C:\projects\automonkeyproject\Sources\AutoMonkey\AMLinLibTest\bin\Debug\AMLinLibTest.dll
    nunit-console C:\projects\automonkeyproject\Sources\AutoMonkey\AMLogEngineLibTest\bin\Debug\AMLogEngineLibTest.dll
    nunit-console C:\projects\automonkeyproject\Sources\AutoMonkey\AutoMonkeyTest\bin\Debug\AutoMonkeyTest.dll
    
