version: 0.0.{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# branches to build
branches:
  only:
    - master

skip_tags: true

skip_commits:
  message: /README.md edited online/
 
cache:
  - packages -> **\packages.config
  - C:\downloads -> appveyor.yml

image: 
  - Visual Studio 2017
  
before_build:
    - nuget restore ./Sources/AutoMonkey/AutoMonkey.sln

build:
  project: ./Sources/AutoMonkey/AutoMonkey.sln
  verbosity: minimal

test:
  assemblies:
    - '**\*Test.dll'

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: '**\*.dll'
    name: AutoMonkeyLib
    type: zip
  
  - path: '**\*.exe'
    name: AutoMonkeyLib
    type: zip

  
 