version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

install: nuget install  NUnit.Console -OutputDirectory %SYSTEMDRIVE%\Tools\NUnit35
set path=%SYSTEMDRIVE%\Tools\NUnit35\NUnit.ConsoleRunner.3.5.0\tools\;%path%
mkdir %SYSTEMDRIVE%\Tools\NUnit35\NUnit.ConsoleRunner.3.5.0\tools\addins
copy %SYSTEMDRIVE%\Tools\NUnit3\bin\addins %SYSTEMDRIVE%\Tools\NUnit35\NUnit.ConsoleRunner.3.5.0\tools\addins
copy c:\Tools\NUnit3\bin\appveyor.addins %SYSTEMDRIVE%\Tools\NUnit35\NUnit.ConsoleRunner.3.5.0\tools



before_build:
    - nuget restore ./Sources/AutoMonkey/AutoMonkey.sln

build:
  project: ./Sources/AutoMonkey/AutoMonkey.sln
  verbosity: minimal

# scripts to run before tests
before_test:
  - echo ========= Runing unit tests ===============

# to run tests again only selected assemblies and/or categories
test:
  assemblies:
    only:
      - '**\*Test.dll'
    
test_script:
- cmd: nunit3-console "C:\projects\automonkeyproject\Sources\AutoMonkey\AMCanUsbLibTest\bin\Debug\AMCanUsbLibTest.dll" "C:\projects\automonkeyproject\Sources\AutoMonkey\AMLinLibTest\bin\Debug\AMLinLibTest.dll" "C:\projects\automonkeyproject\Sources\AutoMonkey\AMLogEngineLibTest\bin\Debug\AMLogEngineLibTest.dll" "C:\projects\automonkeyproject\Sources\AutoMonkey\AutoMonkeyTest\bin\Debug\AutoMonkeyTest.dll"
