version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

before_build:
    - nuget restore ./Sources/AutoMonkey/AutoMonkey.sln

build:
  project: ./Sources/AutoMonkey/AutoMonkey.sln
  verbosity: minimal

# scripts to run before tests
before_test:
  - echo ========= Runing unut tests ===============
  - ps: Write-Host "========= Runing unut tests ==============="

test:
  assemblies:
  only:
  - '**\*Test.dll'

test_script:
- cmd: >-
    nunit-console ./Sources/AutoMonkey/AMCanUsbLibTest/bin/Debug/AMCanUsbLibTest.dll
    nunit-console ./Sources/AutoMonkey/AMLinLibTest/bin/Debug/AMLinLibTest.dll
    nunit-console ./Sources/AutoMonkey/AMLogEngineLibTest/bin/Debug/AMLogEngineLibTest.dll
    nunit-console ./Sources/AutoMonkey/AutoMonkeyTest/bin/Debug/AutoMonkeyTest.dll
    
